# Predicting Life Expectancy with Neural Networks

Embark on a journey into global health insights as we explore the factors influencing life expectancy across countries. The World Health Organization's (WHO) Global Health Observatory (GHO) dataset, spanning 2000 to 2015, provides a rich tapestry of indicators encompassing immunization, mortality, economic, social, and other health-related factors.

### Project Context

In the quest to enhance life expectancy predictions, this project undertakes the task of designing, training, and evaluating a neural network model using regression. Traditionally studied variables such as demographic factors, income composition, and mortality rates are considered, alongside often-overlooked elements like immunization and human development index.

### Dataset Overview

- **Temporal Coverage:** 2000 to 2015
- **Indicators:** Immunization, Mortality, Economic, Social, Health-related Factors
- **Target Variable:** Life Expectancy (Years)

### Initial Data Exploration

To lay the groundwork, the dataset is loaded and explored. Columns are appropriately formatted, and an initial inspection provides an overview of the data's structure and statistical summary.

### Data Preprocessing

Understanding the importance of a unified approach, the 'Country' column is dropped to focus on learning general patterns applicable across countries. The data is then split into labels and features, and numerical features are standardized/normalized for consistent modeling.

### Building the Neural Network Model

With TensorFlow and Keras, a neural network model is crafted. The architecture includes an input layer, a hidden layer with 64 neurons and a ReLU activation function, and an output layer with a single neuron for regression predictions.

### Model Compilation

The model is compiled using the Mean Squared Error (MSE) loss function and Mean Absolute Error (MAE) as a metric. The Adam optimizer with a learning rate of 0.01 is employed.

### Model Training and Evaluation

The model undergoes training with 50 epochs and a batch size of 1. The validation split aids in assessing performance during training. Subsequently, the model is evaluated on the test set, and the MSE and MAE on the test data are reported.

### Key Findings

As we unravel the mysteries of life expectancy prediction, the project aims to uncover patterns that contribute significantly to this vital health indicator. Stay tuned for in-depth insights into the factors that shape the life expectancy landscape globally.

------------

## Data Loading & Exploration

In [61]:
import pandas as pd

# Load the data
dataset = pd.read_csv('data/life_expectancy.csv', delimiter=';', header=0)
dataset

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263,62,0.01,71.279624,65,1154,19.1,...,8.16,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271,64,0.01,73.523582,62,492,18.6,...,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268,66,0.01,73.219243,64,430,18.1,...,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272,69,0.01,78.184215,67,2787,17.6,...,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275,71,0.01,7.097109,68,3013,17.2,...,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,723,27,4.36,0.000000,68,31,27.1,...,7.13,65,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,44.3
2934,Zimbabwe,2003,Developing,715,26,4.06,0.000000,7,998,26.7,...,6.52,68,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5,44.5
2935,Zimbabwe,2002,Developing,73,25,4.43,0.000000,73,304,26.3,...,6.53,71,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0,44.8
2936,Zimbabwe,2001,Developing,686,25,1.72,0.000000,76,529,25.9,...,6.16,75,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,45.3
2937,Zimbabwe,2000,Developing,665,24,1.68,0.000000,79,1483,25.5,...,7.10,78,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8,46.0

In [62]:
# Remove leading spaces & capitalize initial letter of each column name
dataset.columns = dataset.columns.str.strip().str.capitalize()

In [63]:
# Inspect the data
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Adult mortality                  2938 non-null   int64
 4   Infant deaths                    2938 non-null   int64
 5   Alcohol                          2938 non-null   float64
 6   Percentage expenditure           2938 non-null   float64
 7   Hepatitis b                      2938 non-null   int64
 8   Measles                          2938 non-null   int64
 9   Bmi                              2938 non-null   float64
 10  Under-five deaths                2938 non-null   int64
 11  Polio                            2938 non-null   int64
 12  Total expenditure                2938 non-null   float64
 13  Diphtheria                       2938 non-null   int64
 14  Hiv/aids                         2938 non-null   float64
 15  Gdp                              2938 non-null   float64
 16  Population                       2938 non-null   float64
 17  Thinness  1-19 years             2938 non-null   float64
 18  Thinness 5-9 years               2938 non-null   float64
 19  Income composition of resources  2938 non-null   float64
 20  Schooling                        2938 non-null   float64
 21  Life expectancy                  2938 non-null   float64
dtypes: float64(12), int64(8), object(2)
memory usage: 505.1+ KB

In [64]:
# Get the summary statistics
dataset.describe()

,Year,Adult mortality,Infant deaths,Alcohol,Percentage expenditure,Hepatitis b,Measles,Bmi,Under-five deaths,Polio,Total expenditure,Diphtheria,Hiv/aids,Gdp,Population,Thinness 1-19 years,Thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
count,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000,2.938000e+03,2938.000000,2938.000000,2938.000000,2938.000000,2938.000000
mean,2007.518720,164.725664,30.303948,4.546875,738.251295,83.022124,2419.592240,38.381178,42.035739,82.617767,5.924098,82.393125,1.742103,6611.523863,1.023085e+07,4.821886,4.852144,0.630362,12.009837,69.234717
std,4.613841,124.086215,117.926501,3.921946,1987.914858,22.996984,11467.272489,19.935375,160.445548,23.367166,2.400770,23.655562,5.077785,13296.603449,5.402242e+07,4.397621,4.485854,0.205140,3.265139,9.509115
min,2000.000000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,36.300000
25%,2004.000000,74.000000,0.000000,1.092500,4.685343,82.000000,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,580.486996,4.189172e+05,1.600000,1.600000,0.504250,10.300000,63.200000
50%,2008.000000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.755000,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000,72.100000
75%,2012.000000,227.000000,22.000000,7.390000,441.534144,96.000000,360.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,4779.405190,4.584371e+06,7.100000,7.200000,0.772000,14.100000,75.600000
max,2015.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000,89.000000

Next I drop the country column. Given that I want to learn a general pattern for all the countries, and not only those dependent on specific countries.

In [65]:
# Drop 'countries' column
dataset.drop(['Country'], inplace=True, axis=1) 
dataset

,Year,Status,Adult mortality,Infant deaths,Alcohol,Percentage expenditure,Hepatitis b,Measles,Bmi,Under-five deaths,...,Total expenditure,Diphtheria,Hiv/aids,Gdp,Population,Thinness 1-19 years,Thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,2015,Developing,263,62,0.01,71.279624,65,1154,19.1,83,...,8.16,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,2014,Developing,271,64,0.01,73.523582,62,492,18.6,86,...,8.18,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,2013,Developing,268,66,0.01,73.219243,64,430,18.1,89,...,8.13,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,2012,Developing,272,69,0.01,78.184215,67,2787,17.6,93,...,8.52,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,2011,Developing,275,71,0.01,7.097109,68,3013,17.2,97,...,7.87,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,Developing,723,27,4.36,0.000000,68,31,27.1,42,...,7.13,65,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,44.3
2934,2003,Developing,715,26,4.06,0.000000,7,998,26.7,41,...,6.52,68,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5,44.5
2935,2002,Developing,73,25,4.43,0.000000,73,304,26.3,40,...,6.53,71,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0,44.8
2936,2001,Developing,686,25,1.72,0.000000,76,529,25.9,39,...,6.16,75,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,45.3
2937,2000,Developing,665,24,1.68,0.000000,79,1483,25.5,39,...,7.10,78,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8,46.0

Next I split the data into labels and features.

In [66]:
# Assign final column to labels
labels = dataset.iloc[:, -1]

# Assign all but the final column to features
features = dataset.iloc[:, :-1]

## Data Preprocessing

In [67]:
# Apply one-hot encoder to features
features = pd.get_dummies(features)
features

,Year,Adult mortality,Infant deaths,Alcohol,Percentage expenditure,Hepatitis b,Measles,Bmi,Under-five deaths,Polio,...,Diphtheria,Hiv/aids,Gdp,Population,Thinness 1-19 years,Thinness 5-9 years,Income composition of resources,Schooling,Status_Developed,Status_Developing
0,2015,263,62,0.01,71.279624,65,1154,19.1,83,6,...,65,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,False,True
1,2014,271,64,0.01,73.523582,62,492,18.6,86,58,...,62,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,False,True
2,2013,268,66,0.01,73.219243,64,430,18.1,89,62,...,64,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,False,True
3,2012,272,69,0.01,78.184215,67,2787,17.6,93,67,...,67,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,False,True
4,2011,275,71,0.01,7.097109,68,3013,17.2,97,68,...,68,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,2004,723,27,4.36,0.000000,68,31,27.1,42,67,...,65,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,False,True
2934,2003,715,26,4.06,0.000000,7,998,26.7,41,7,...,68,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5,False,True
2935,2002,73,25,4.43,0.000000,73,304,26.3,40,73,...,71,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0,False,True
2936,2001,686,25,1.72,0.000000,76,529,25.9,39,76,...,75,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,False,True
2937,2000,665,24,1.68,0.000000,79,1483,25.5,39,78,...,78,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8,False,True

In [68]:
from sklearn.model_selection import train_test_split

# Split data into training set and test
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state=42)

Next I standardize/normalize the numerical features.

In [69]:
from sklearn.preprocessing import StandardScaler
#from sklearn.preprocessing import Normalizer
from sklearn.compose import ColumnTransformer

# Identify numeric features
numerical_features = features.select_dtypes(include=['float64', 'int64'])
numerical_columns = numerical_features.columns

# Instantiate ColumnTransformer using StandardScaler on numeric columns
ct = ColumnTransformer([("only numeric", StandardScaler(), numerical_columns)], remainder='passthrough')

# Apply scaler to training and test data
features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.transform(features_test)

## Building the Model

In [73]:
import tensorflow as tf
import keras 

# Define the model
model = tf.keras.models.Sequential()

# Create input layer with shape corresponding to the number of features in dataset
input = tf.keras.Input(shape=(features.shape[1],))

# Add layers to network model
model.add(input) # Add input layer to model
model.add(tf.keras.layers.Dense(64, activation='relu')) # Add hidden layer to model
model.add(tf.keras.layers.Dense(1)) # Add output layer to model - one neuron since we need a single output for a regression prediction

# Print model summary
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                1408

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 1473 (5.75 KB)
Trainable params: 1473 (5.75 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None

## Initializing the optimizer and compiling the model

In [74]:
# Create an instance of the Adam optimizer with the learning rate equal to 0.01
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

# Compile model
model.compile(loss='mse', metrics=['mae'], optimizer=opt)

## Fit and evaluate the model

In [75]:
# Train model with the Sequential.fit() method
model.fit(features_train_scaled, labels_train, epochs=50, batch_size=1, verbose=1, validation_split=0.2)

Epoch 1/50
1880/1880 [==============================] - 4s 2ms/step - loss: 189.0699 - mae: 7.4101 - val_loss: 28.6177 - val_mae: 4.2264
Epoch 2/50
1880/1880 [==============================] - 4s 2ms/step - loss: 25.7059 - mae: 3.7765 - val_loss: 18.3617 - val_mae: 3.2282
Epoch 3/50
1880/1880 [==============================] - 4s 2ms/step - loss: 24.2834 - mae: 3.7248 - val_loss: 33.4869 - val_mae: 4.8261
Epoch 4/50
1880/1880 [==============================] - 4s 2ms/step - loss: 29.3443 - mae: 3.6334 - val_loss: 10.4231 - val_mae: 2.4024
Epoch 5/50
1880/1880 [==============================] - 4s 2ms/step - loss: 23.5953 - mae: 3.4211 - val_loss: 46.5300 - val_mae: 5.4950
Epoch 6/50
1880/1880 [==============================] - 4s 2ms/step - loss: 17.8425 - mae: 3.1306 - val_loss: 19.6917 - val_mae: 3.2856
Epoch 7/50
1880/1880 [==============================] - 4s 2ms/step - loss: 19.7974 - mae: 3.0852 - val_loss: 15.8393 - val_mae: 3.0962
Epoch 8/50
1880/1880 [==============================] - 4s 2ms/step - loss: 18.4376 - mae: 3.0179 - val_loss: 21.2152 - val_mae: 3.7353
Epoch 9/50
1880/1880 [==============================] - 4s 2ms/step - loss: 14.3627 - mae: 2.7749 - val_loss: 22.4922 - val_mae: 3.6361
Epoch 10/50
1880/1880 [==============================] - 4s 2ms/step - loss: 14.1703 - mae: 2.7535 - val_loss: 19.2620 - val_mae: 3.3650
Epoch 11/50
1880/1880 [==============================] - 4s 2ms/step - loss: 13.8410 - mae: 2.7225 - val_loss: 10.4432 - val_mae: 2.4386
Epoch 12/50
1880/1880 [==============================] - 4s 2ms/step - loss: 10.6039 - mae: 2.4583 - val_loss: 19.2321 - val_mae: 3.2365
Epoch 13/50
1880/1880 [==============================] - 3s 2ms/step - loss: 12.8326 - mae: 2.5382 - val_loss: 8.7974 - val_mae: 2.2072
Epoch 14/50
1880/1880 [==============================] - 4s 2ms/step - loss: 11.1994 - mae: 2.4298 - val_loss: 9.8787 - val_mae: 2.3349
Epoch 15/50
1880/1880 [==============================] - 4s 2ms/step - loss: 10.2638 - mae: 2.3265 - val_loss: 10.5673 - val_mae: 2.4430
Epoch 16/50
1880/1880 [==============================] - 4s 2ms/step - loss: 10.2432 - mae: 2.3748 - val_loss: 16.8954 - val_mae: 3.1947
Epoch 17/50
1880/1880 [==============================] - 4s 2ms/step - loss: 10.1199 - mae: 2.3530 - val_loss: 7.7001 - val_mae: 2.0084
Epoch 18/50
1880/1880 [==============================] - 4s 2ms/step - loss: 11.4003 - mae: 2.3465 - val_loss: 12.3199 - val_mae: 2.6985
Epoch 19/50
1880/1880 [==============================] - 4s 2ms/step - loss: 12.1320 - mae: 2.4340 - val_loss: 8.1633 - val_mae: 2.1483
Epoch 20/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.3061 - mae: 2.1474 - val_loss: 9.0071 - val_mae: 2.2684
Epoch 21/50
1880/1880 [==============================] - 4s 2ms/step - loss: 10.4132 - mae: 2.3099 - val_loss: 8.3714 - val_mae: 2.0561
Epoch 22/50
1880/1880 [==============================] - 4s 2ms/step - loss: 9.0571 - mae: 2.1721 - val_loss: 8.2382 - val_mae: 2.0453
Epoch 23/50
1880/1880 [==============================] - 4s 2ms/step - loss: 9.6682 - mae: 2.1852 - val_loss: 8.4906 - val_mae: 2.0476
Epoch 24/50
1880/1880 [==============================] - 4s 2ms/step - loss: 11.1437 - mae: 2.3014 - val_loss: 9.5987 - val_mae: 2.2785
Epoch 25/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.2147 - mae: 2.1368 - val_loss: 10.9319 - val_mae: 2.5178
Epoch 26/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.4975 - mae: 2.1298 - val_loss: 8.6582 - val_mae: 2.0677
Epoch 27/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.5291 - mae: 2.0372 - val_loss: 13.2155 - val_mae: 2.7343
Epoch 28/50
1880/1880 [==============================] - 4s 2ms/step - loss: 9.2521 - mae: 2.1257 - val_loss: 11.4115 - val_mae: 2.4990
Epoch 29/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.7193 - mae: 2.1469 - val_loss: 7.6496 - val_mae: 2.0223
Epoch 30/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.1086 - mae: 2.1255 - val_loss: 12.0477 - val_mae: 2.5624
Epoch 31/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.7223 - mae: 2.1135 - val_loss: 10.0813 - val_mae: 2.3430
Epoch 32/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.5064 - mae: 2.0440 - val_loss: 9.2738 - val_mae: 2.2038
Epoch 33/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.4824 - mae: 2.0523 - val_loss: 8.4232 - val_mae: 2.1812
Epoch 34/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.0161 - mae: 2.0817 - val_loss: 8.5605 - val_mae: 2.0542
Epoch 35/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.4064 - mae: 2.0778 - val_loss: 8.0210 - val_mae: 1.9585
Epoch 36/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.0111 - mae: 1.9800 - val_loss: 11.1020 - val_mae: 2.4409
Epoch 37/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.0047 - mae: 2.0383 - val_loss: 8.6353 - val_mae: 2.1178
Epoch 38/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.4310 - mae: 2.0432 - val_loss: 9.8954 - val_mae: 2.2776
Epoch 39/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.0199 - mae: 1.9860 - val_loss: 8.5850 - val_mae: 2.0511
Epoch 40/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.0020 - mae: 1.9844 - val_loss: 12.2388 - val_mae: 2.6402
Epoch 41/50
1880/1880 [==============================] - 4s 2ms/step - loss: 8.4042 - mae: 2.1083 - val_loss: 8.7093 - val_mae: 2.1545
Epoch 42/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.8047 - mae: 2.0328 - val_loss: 8.2433 - val_mae: 2.0462
Epoch 43/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.6064 - mae: 1.9893 - val_loss: 8.1838 - val_mae: 2.0252
Epoch 44/50
1880/1880 [==============================] - 4s 2ms/step - loss: 6.3343 - mae: 1.9029 - val_loss: 7.3661 - val_mae: 1.9662
Epoch 45/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.8365 - mae: 2.0407 - val_loss: 10.2482 - val_mae: 2.3291
Epoch 46/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.3084 - mae: 1.9791 - val_loss: 8.1562 - val_mae: 2.0214
Epoch 47/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.5148 - mae: 2.0267 - val_loss: 8.7078 - val_mae: 2.1897
Epoch 48/50
1880/1880 [==============================] - 4s 2ms/step - loss: 6.4976 - mae: 1.9012 - val_loss: 9.4448 - val_mae: 2.2920
Epoch 49/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.4806 - mae: 2.0089 - val_loss: 8.7166 - val_mae: 2.0685
Epoch 50/50
1880/1880 [==============================] - 4s 2ms/step - loss: 7.1944 - mae: 1.9294 - val_loss: 11.7392 - val_mae: 2.6421

In [77]:
# Evaluate model with the Sequential.evaluate() method
rse_mse, rse_mae = model.evaluate(features_test_scaled, labels_test, verbose=0)
print('Mean squared error on test data: {:.2f}'.format(rse_mse))
print('Mean absolute error on test data: {:.2f}'.format(rse_mae))

Mean squared error on test data: 9.94
Mean absolute error on test data: 2.47